### PR TITLE
Fix select not working on React 18 / Testing Library  React 13

### PR DESCRIPTION
**Pull request by bramdevries**
Fixes https://github.com/romgain/react-select-event/issues/88

The main issue seemed to be because of logic to open / select the option being wrapped in the `act` call as this prevented the options from being visible. I suppose `testing-library/react` made some changes to make this not needed anymore. Now, only the `fireEvent.click` call is wrapped in an `act`.

I've also tested these changes in an actual project that has some more complex interactions and they no longer have an issue with `react-select-event`.

### CODE REVIEW

**Comment by bramdevries** [comment]
@romgain Any chance you could have a look at this PR? This package is one of the few ones that's blocking us from upgrading to React 18.

**Comment by bramdevries** [comment]
I've reverted the dev dependencies back to their original so the `tav` test is able to run correctly.

**Comment by bramdevries** [comment]
I think I fixed the last bug which was the `@types/react` dependency being updated to React 18 (also causes the current `master` branch to fail).

I ran a separate test suite on React 18 and didn't notice any failures so the fix is compatible with React 17 and 18.

**Comment by bramdevries** [comment]
@romgain I think this is good to go now?

**Comment by bramdevries** [comment]
@romgain Sorry to ping you again but any chance you could take another look at this?

**Comment by romgain** [comment]
@bramdevries thanks again!

I know it’s taking a while, but unfortunately this will probably have to wait until next week :(

**Review by romgain — APPROVED** [review]

**Comment by romgain** [comment]
Thanks @bramdevries - this is now available in v5.5.1 🎉

**Pull request merged**
