### PR TITLE
Dynamically get react-select parent

### PR DESCRIPTION
**Pull request by th3fallen**
Get react-select parent using .closest and attribute matchers to match dynamically generated class ex: `.css-ab123s-container`

### CODE REVIEW

**Comment by romgain** [comment]
Hi @th3fallen !
Thank you very much for your contribution!

it looks like your commit didn’t pass the CI checks: would you mind running `npm run prettier:apply` to fix this error?

It would also be awesome if you could check the output of `npm run test:all-versions` to make sure that your change doesn’t break compatibility with older versions of react-select. 

Thanks again!

**Comment by th3fallen** [comment]
Ah sorry about that yep I’ll get that fixed up today!

**Comment by th3fallen** [comment]
that _should_ fix it up, while i hate the need for two... stupid emotion spaces

**Comment by th3fallen** [comment]
looks like it fails coverage on my fork, I honestly have no idea how to test that fallback selector, any suggestions?

**Comment by romgain** [comment]
Oh apologies - I don’t think you’ll be able to cover this. 

Feel free to add an “Istanbul ignore if” comment to skip this

**Comment by th3fallen** [comment]
done, i hate adding those so just wanted to make sure that was ok by you.

**Review by romgain — APPROVED** [review]

**Comment by romgain** [comment]
Thanks again!
v5.4.0 is now available on npm :-)

**Comment by romgain** [comment]
btw, I think that https://github.com/romgain/react-select-event/pull/54 can be fixed using the exact same mechanism - if you feel like it, a PR that fixes it would be greatly appreciated! 😄

**Comment by th3fallen** [comment]
@romgain yeah i'll take a look, but from a precursery glance this change may actually already fix it...

**Pull request merged**
